#ifndef BUZZER_IOCTL_H
#define BUZZER_IOCTL_H

#define NUMBER_START 0x80
#define NUMBER1 NUMBER_START+1
#define NUMBER2 NUMBER_START+2

#define MAGIC_NUMBER 'z'
#define BUZZER_ON_CMD _IO(MAGIC_NUMBER, NUMBER1)
#define BUZZER_OFF_CMD _IO(MAGIC_NUMBER, NUMBER2)

#endif